# Table of Contents
 <p>

READ (described in Sec. 3.2),
WRITE (described in Sec. 3.2).

ZERO(a, b) = 0, 
ONE(a, b) = 1, 
TWO(a, b) = 2, 

INC(a, b) = (a+1) mod M, 
ADD(a, b) = (a+b) mod M, 
SUB(a, b) = (a−b) mod M, 
DEC(a, b) = (a−1) mod M, 
LESS-THAN(a, b) = [a < b], 
LESS-OR-EQUAL-THAN(a, b) = [a ≤ b], 
EQUALITY-TEST(a, b) = [a = b], 
MIN(a, b) = mod M, 
SUB(a, b) = (a−b) mod M, 
DEC(a, b) = (a−1) mod M, 
LESS-THAN(a, b) = [a < b], 
LESS-OR-EQUAL-THAN(a, b) = [a ≤ b], 
EQUALITY-TEST(a, b) = [a = b], 
MIN(a, b) = min(a, b), 
MAX(a, b) = max(a, b), 
LESS-OR-EQUAL-THAN(a, b) = [a ≤ b], 
EQUALITY-TEST(a, b) = [a = b], 
MIN(a, b) = min(a, b), 
MAX(a, b) = max(a, b), 


In [1]:
import numpy as np
import theano

from theano import tensor
from collections import namedtuple
from theano.tensor.extra_ops import to_one_hot
from theano.tensor import roll
from theano.tensor import stack
from theano.tensor import batched_dot
from theano.tensor import concatenate
from theano.tensor import as_tensor
from theano.tensor import set_subtensor
from theano import shared
from numpy.random import uniform
from theano.tensor.nnet import softmax, relu, sigmoid
from theano import function, config, shared, sandbox, Out

def zero() :
    return to_one_hot(np.asarray([0]),M)
def one() :
    return to_one_hot(np.asarray([1]),M)
def two() :
    return to_one_hot(np.asarray([2]),M)
def get_const(value) :
    return to_one_hot(np.asarray([value % M]),M)
def create_memory_tape(init_val=0):
    m = stack([get_const(init_val) for i in range(M)], axis=1)
    #return shared(np.asarray(m.eval()), config.floatX) 
    return m
def inc(a) :
    return roll(a, 1, axis=1)
def negate(a) :
    return roll(a[:, ::-1], 1, axis=1)
def add(a,b) :
    rows = [roll(b[:,], j, axis=1) for j in range(M)]
    return (batched_dot(a, stack(rows, axis=1)))
def sub(a,b) :
    b_negative = negate(b)
    return add(a, b_negative)
def eq_zero(a) :
    r = tensor.zeros_like(as_tensor(a))
    r = set_subtensor(r[:,1], a[:, 0])
    r = set_subtensor(r[:, 0], 1 - a[:, 0])
    return r
def lt(a,b):
    a = as_tensor(a)
    b = as_tensor(b)
    b = set_subtensor(b[:,0], [0]) 
    b = roll(b[:,], -1, axis=1)
    rows = [set_subtensor(tensor.zeros_like(as_tensor(b))[:,j:M], b[:,j:M]) for j in range(M)]
    result = ((tensor.dot(as_tensor(a), stack(rows, axis =1))).sum()).dimshuffle('x')
    return set_subtensor(tensor.zeros_like(as_tensor(b))[:,1], result)
def eq(a,b):
    elemwise_result = tensor.eq(as_tensor(a),as_tensor(b))
    sum = elemwise_result.sum()
    result = tensor.eq(sum,M).dimshuffle('x')
    return set_subtensor(tensor.zeros_like(as_tensor(a))[:,1], result)
def max_(a,b):
    if(tensor.eq([0],lt(a,b))):
        return as_tensor(b)
    else:
        return as_tensor(a)
def min_(a,b):
    if(tensor.eq([1],lt(a,b))):
        return as_tensor(a)
    else:
        return as_tensor(b)    
def read(mem, a) :
    ptr = as_tensor(a)
    return weighted_avg(mem, ptr), mem
def write(mem, a, b) :
    ptr = as_tensor(a)
    val = as_tensor(b)
    J = (tensor.ones_like(zero())).T
    erase_vector = (J-ptr.T).dot(J.T)
    x = tensor.mul(erase_vector, mem)
    y = (ptr.T).dot(val)
    mem = (x + y)
    return val, mem
def write_external(a, b, ext_mem) :
    ptr = as_tensor(a)
    val = as_tensor(b)
    J = (tensor.ones_like(zero())).T
    erase_vector = (J-ptr.T).dot(J.T)
    x = tensor.mul(erase_vector, ext_mem)
    y = (ptr.T).dot(val)
    ext_mem = (x + y)
    return ext_mem

def get_registers(init_val):
    return stack([get_const(init_val) for i in range(R)], axis=1)

def weighted_avg(inputs, coefficient) :
    return batched_dot(inputs.transpose(0, 2, 1), coefficient.dimshuffle(0, 1, 'x')).flatten(2);

def compute_gate_new(module, inputs, coefficients, memory_tape, debug=False) :
    """ Arity of this gate must be equal to the number of given
        coefficients list
    """ 
    if (len(coefficients) != module.arity) :
        print("Error: Incorrect number of coefficients: ",  len(coefficients), " to module arity: ", module.arity)
    
    params = [weighted_avg(inputs, as_tensor(coef)) for coef in coefficients]
    
    if (debug == True):
        for i, p in enumerate(params):
            print("compute_gate_new: coeff", coefficients[i].eval(), " weighted param [", i ,"] = ", p.eval().argmax())
    
    if (module.memory_function == True) :
        #print("read/write ")
        output, memory_tape = module.function(memory_tape, *params)
    else :   
        output = module.function(*params)
    
    #error check for constant gates
    return output, memory_tape


def get_n_tensor(t, count, idx):
    result=[]
    if count > 0: 
        result = [t[idx+i] for i in range(count)]
    return result, (idx+count)

def fuzzy_circuit(registers, gates, memory_tape, gate_coef, reg_coef, debug=False):
    # Initially, only the registers may be used as inputs.
    Q= len(gates)
    gate_inputs = registers
    idx=0    
    
    # Run through all the gates.
    for i in range(Q):
        c, idx = get_n_tensor(gate_coef, gates[i].arity, idx) 
        if (debug==True):
            print("gate i = ", i, "arity:", gates[i].arity, "gate inputs: ", gate_inputs.eval().argmax(axis=2))
        output, memory_tape = compute_gate_new(gates[i], gate_inputs, c, memory_tape, debug)
        # Append the output of the gate as an input for future gates.
        gate_inputs = concatenate([gate_inputs, output.dimshuffle(0,'x',1)], axis=1)
        if (debug==True):
            print("gate output: ", output.eval().argmax())    
            print("concatenated inputs: ", gate_inputs.eval().argmax(axis=2))       
        
    # All leftover coefficients are for registers.
    new_registers = []
             
    for i in range(len(reg_coef)):
        # (R+Q) x M dot 1 X (R+Q) 
        new_registers.append(weighted_avg(gate_inputs, reg_coef[i]))
        if (debug == True) :
            print("register [", i, "]  new value: reg_coef", reg_coef[i].eval().argmax(),"weighted_avg of gate inputs and reg_coef: ", weighted_avg(gate_inputs, reg_coef[i]).eval().argmax())
    return tensor.stack(new_registers, axis=1), memory_tape


# coefficients = [r1,r2..rR,g1_param1,g1_param2,...,gQ_param1,gQ_param2,c1,c1..CR,cR+1,..cR+Q]
def gen_random_weights(layer1, layer2, dtype=np.float64, _min=-1, _max=1):
    weights = uniform(low=_min, high=_max, size=(layer1, layer2))
    var = shared(weights.astype(dtype), name="w{0}x{1}".format(layer1, layer2))   
    #var = tensor.addbroadcast(var, 0)
    return var

def gen_network_weights(gates, layers):
    n_registers = R #input is R registers
    w = []
    current_layer_units = n_registers
    for next_layer_units in layers:
        w.append(gen_random_weights(current_layer_units + 1, next_layer_units))
        current_layer_units = next_layer_units
    #output wt for gate coefficients
    gate_coef = []
    for i, gate in enumerate(gates):
        print(i, gate)
        #each param to gates are R+i depending on arity 
        gate_output_units = n_registers + i
        for _ in range(gate.arity):
            gate_coef.append(gen_random_weights(current_layer_units + 1, gate_output_units))            
    
    #print("gen_network_weights => gate_coef", gate_coef)         
    #output wt for new registers
    reg_coef = []
    reg_output_units = n_registers + len(gates)
    for _ in range(n_registers):
        reg_coef.append(gen_random_weights(current_layer_units + 1, n_registers + len(gates)))    
    
    #print("gen_network_weights => reg_coef", reg_coef)      
    prob_completion_coef = (gen_random_weights(current_layer_units + 1, 1))

    for i in gate_coef:
        w.append(i)

    for x in reg_coef:
        w.append(x)
    
    w.append(prob_completion_coef)   
    return w

def aug_ones_col(inputs):
    print("OMFG")
    s = inputs.shape
    col_elems = s[1]
    ones = tensor.ones_like(to_one_hot(np.asarray([0]), col_elems))
    x = concatenate([inputs.T,ones], axis=1)
    return x.T

def aug_ones_col_new(inputs):
    x=[]
    s = inputs.shape
    d = inputs.ndim
    row_elems = s[d-2]
    matrix = tensor.reshape(inputs, (s[d-2],s[d-1]))
    matrix = tensor.shape_padleft(matrix)
    ones = tensor.ones_like(to_one_hot(np.asarray([0]), row_elems))
    x = concatenate([matrix.dimshuffle(0,2,1),ones.dimshuffle(0,'x',1)], axis=1)
    return x.dimshuffle(0,2,1)

def controller_forward_prop(n_registers, layers, weight_matrix, gates, registers, debug) :
    inputs = aug_ones_col_new(registers[:,:,0])
    if (debug == True):
        print("registers: ", registers.eval())
        print("registers[:,:,0]: ", registers[:,:,0].eval())
        print("inputs: ", inputs.eval())
        
    for i in range(len(layers)):
        W = weight_matrix[i]
        inputs = aug_ones_col_new(relu(inputs.dot(W)))  
        if (debug == True):
            print("compute layers inputs: ", inputs.eval())
    
    #extract gate coefficients
    gate_coef = []
    n_gate_coef = 0
    
    for i, gate in enumerate(gates): 
        #each param to gates are R+i depending on arity 
        gate_output_units = n_registers + i
        for _ in range(gate.arity):
            n_gate_coef += 1  
            
    for W in weight_matrix[len(layers):len(layers) + n_gate_coef]:
        gate_coef.append(softmax(inputs.dot(W)[0]))            
    
    reg_coef = []
    for W in (weight_matrix[len(layers)+n_gate_coef:len(layers)+n_gate_coef+n_registers]):
        reg_coef.append(softmax(inputs.dot(W)[0]))  
    
    if (debug == True):
        print("inputs.dot(W)", inputs.dot(W).eval())
        print("inputs.dot(W)[0]", inputs.dot(W)[0].eval())
        print("p_complete inputs: ", inputs.eval())
        print("inputs.dot(weight_matrix[-1]: ", inputs.dot(weight_matrix[-1]).eval())  
              
    p = sigmoid((inputs.dot(weight_matrix[-1])))
    if (debug == True):
        print("p_complete: ", p.eval())
        
    return p, reg_coef, gate_coef

def calculate_cost_at_t(prob_complete_t, t, cum_cost, cum_prob_t, p_incomplete, memory_in, desired_output, output_len, debug) :
    e_min = 1e-100
    e_max = 1e+100
    cost_t = 0
    #TODO: Find use for desired registers in calculating cost. Now, only desired memory layout is matched.
    for i in range(output_len):
        #Compute the loss for this register using the mask.
        y = to_one_hot(desired_output.argmax(axis=2)[:,i], M)   
        y_hat = to_one_hot(memory_in.argmax(axis=2)[:,i], M) 
        ln_y_hat = tensor.log(tensor.clip(memory_in[:, i, :], e_min, e_max))
        ln_1_minus_y_hat = tensor.log(tensor.clip(1 - memory_in[:, i, :], e_min, e_max))
        x1 = y * ln_y_hat
        x2 = (1 - y) * ln_1_minus_y_hat
        loss = (x1+x2).sum(axis=1) 
        cost_t += tensor.shape_padright(loss, 1)
        if (debug == True):
            #print("desired_output at i", desired_output[:,i].eval())
            #print("memory value at i", memory_in[:, i, :].eval())
            #print("y ", y.eval())
            #print("y_hat ", y_hat.eval())
            #print("ln_y_hat ", ln_y_hat.eval())
            #print("ln_1_minus_y_hat ", ln_1_minus_y_hat.eval())
            #print("x1 ", x1.eval())
            #print("x2 ", x2.eval())
            print("loss ", loss.eval())
            #print("tensor.shape_padright(loss, 1) ", tensor.shape_padright(loss, 1).eval())
            #print("Desired value at mem location [", i, "] is ", y.eval().argmax(), "but actual value is [", memory_in[:,i,:].eval().argmax(), "loss is ", loss.eval(), " cost = ", cost_t.eval()) 
    
    if (t == MAX_TIMESTEP):
        prob_complete = 1 - cum_prob_t
    else:
        prob_complete = (prob_complete_t * p_incomplete)
    
    cum_prob_t += prob_complete
    p_incomplete *= (1 - prob_complete_t)
    cum_cost -= (cost_t*prob_complete)
    
    if (debug == True):
        print("prob_complete_t", prob_complete_t.eval())
        print("p_incomplete", p_incomplete.eval())
        print("prob_complete", prob_complete.eval())
        print("cum_prob_t", cum_prob_t.eval())
        print("cost_t*prob_complete", (cost_t*prob_complete).eval())
        print("cum_cost", cum_cost.eval())
    return cum_cost, cum_prob_t, p_incomplete

def machine_compute_step_t(debug, R, layers, w, gates, t, desired_output, output_len, registers, memory_tape, cost_t, cum_prob, prob_incomplete) : 
    prob_complete_t, reg_coef, gate_coef = controller_forward_prop(R, layers, w, gates, registers, debug)
    new_registers, new_memory_tape = fuzzy_circuit(registers, gates, memory_tape, gate_coef, reg_coef, debug)
    cost_t, cum_prob_t, prob_incomplete = calculate_cost_at_t(prob_complete_t, t, cost_t, cum_prob, prob_incomplete, new_memory_tape, desired_output, output_len, debug)
    return new_registers, new_memory_tape, cost_t, cum_prob_t, prob_incomplete

def compute_all_timesteps(gates, layers, registers, memory_tape, w, reg_lambda, output_len):
    #w = make_broadcastable(w)
    # Create symbolic variables for the input to the machine
    # and for the desired output of the machine.
      
    #initial_registers = registers
    #desired_output = memory_tape

    initial_registers = tensor.dtensor3("Registers")
    initial_memory = tensor.dtensor3("Memory_Tape")
    desired_output = tensor.dtensor3("Y")
     
    
    # Run the model for all timesteps. The arguments are 
    # registers, cost, cumulative probability complete, 
    # and probability incomplete. The latter are initialized
    # to zero and to one, respectively.
    
    v0 = as_tensor(0)
    v1 = as_tensor(1)
    output = [initial_registers, initial_memory, v0, v0, v1]
    intermediate_registers = []
    for timestep in range(MAX_TIMESTEP):
        print("compute_all_timesteps t = ", timestep)
        output = machine_compute_step_t(False, R, layers, w, gates, timestep+1, desired_output, output_len, *(output))
        intermediate_registers.append(output[0])

    # Add in regularization, to avoid overfitting simple examples.
    reg_cost = reg_lambda * sum((p * p).sum() for p in list(w))
    
    # Get the final cost: regularization plus loss.
    final_cost = reg_cost + output[2].sum()
    
    # Return the symbolic variables, the final cost, and the
    # intermediate register values for analysis and prediction.
    return initial_registers, initial_memory, desired_output, final_cost, intermediate_registers


In [2]:
#Maximum Representable Integer M is set below
M = 16
# Number of registers
R = 2
#Max number of timesteps
MAX_TIMESTEP = 5

Module = namedtuple("Module", "arity function memory_function")

m_zero = Module(0, zero, False)
m_one = Module(0, one, False)
m_two = Module(0, two, False)
m_inc = Module(1, inc, False)
m_negate = Module(1, negate, False)
m_add = Module(2, add, False)
m_sub = Module(2, sub, False)
m_eq_zero = Module(1, eq_zero, False)
m_read = Module(1, read, True)
m_write = Module(2, write, True)
m_lt = Module(2, lt, False)
m_eq = Module(2, eq, False)
m_min = Module(2, min_, False)
m_max = Module(2, max_, False)

gates = [m_read, m_inc, m_zero, m_lt, m_min, m_write]
#gates = [m_read, m_write]
N = len(gates)

registers = get_registers(1)
memory_tape = create_memory_tape()
desired_out = create_memory_tape(0)
for i in range(M):
     desired_out = write_external(get_const(i), get_const(i), desired_out)
        
layers = [5,5]
w = gen_network_weights(gates, layers)
print("weight matrix: ", w)

(0, Module(arity=1, function=<function read at 0x106b3c758>, memory_function=True))
(1, Module(arity=1, function=<function inc at 0x106b3c320>, memory_function=False))
(2, Module(arity=0, function=<function zero at 0x106b39d70>, memory_function=False))
(3, Module(arity=2, function=<function lt at 0x106b3c578>, memory_function=False))
(4, Module(arity=2, function=<function min_ at 0x106b3c6e0>, memory_function=False))
(5, Module(arity=2, function=<function write at 0x106b3c7d0>, memory_function=True))
('weight matrix: ', [w3x5, w6x5, w6x2, w6x3, w6x5, w6x5, w6x6, w6x6, w6x7, w6x7, w6x8, w6x8, w6x1])


In [3]:
reg_lambda = 0.1
output_len = 1
result  = compute_all_timesteps(gates, layers, registers, memory_tape, w, reg_lambda, output_len)
initial_registers, initial_memory, desired_output, final_cost, intermediate_registers = result

('compute_all_timesteps t = ', 0)
('compute_all_timesteps t = ', 1)
('compute_all_timesteps t = ', 2)
('compute_all_timesteps t = ', 3)
('compute_all_timesteps t = ', 4)


In [4]:
initial_registers, initial_memory, desired_output, final_cost, intermediate_registers

(Registers,
 Memory_Tape,
 Y,
 Elemwise{add,no_inplace}.0,
 [Join.0, Join.0, Join.0, Join.0, Join.0])

In [5]:
gradients = theano.grad(final_cost, list(w)) #, disconnected_inputs='warn', return_disconnected='Disconnected')


In [6]:
for i in range(len(gradients)):
    theano.gradient.grad_clip(gradients[i], -1, 1)

In [7]:
# Compile training function to compute gradients.
train = theano.function([initial_registers, initial_memory, desired_output], [final_cost] + gradients) #, on_unused_input='ignore', allow_input_downcast=True)

In [8]:
#Access Task
input = [ 7,  1,  12,  4,  7,  12,  1,  13,  8,  2, 1, 3, 11, 11, 12, 0]
output = [ 13 ]
registers = get_registers(0)
memory_tape = stack([get_const(i) for i in input], axis=1)
desired_out = stack([get_const(i) for i in output], axis=1)

In [9]:
print ("desired_out.eval()", desired_out.eval().argmax(axis=2))
print ("memory_tape.eval()", memory_tape.eval().argmax(axis=2))
print ("registers.eval()", registers.eval().argmax(axis=2))

('desired_out.eval()', array([[13]]))
('memory_tape.eval()', array([[ 7,  1, 12,  4,  7, 12,  1, 13,  8,  2,  1,  3, 11, 11, 12,  0]]))
('registers.eval()', array([[0, 0]]))


In [10]:
for i in range(1):
    output_train = train(registers.eval(), memory_tape.eval(), desired_out.eval())
    cost = output_train[0]
    gradients = output_train[1:]
    print(output_train)

[array(71.3329429218814), array([[  4.31705273e-02,   2.24454106e+01,  -6.92314258e-02,
          1.09350466e-01,  -3.34101883e+01],
       [  8.70542068e-02,   2.24745801e+01,  -1.27420656e-01,
          1.19600193e-02,  -3.34715117e+01],
       [  4.61696860e-01,   2.26276974e+01,   3.55621368e-02,
          2.03705002e-01,  -3.34777990e+01]]), array([[ -1.43639274e-01,  -9.93335076e-02,  -1.39343930e-01,
         -1.22061298e-01,  -1.96829202e-01],
       [ -1.13655509e-01,  -1.20973178e-02,  -7.59040180e+00,
         -5.03303054e+01,  -4.67424000e+01],
       [ -9.36121738e-02,  -7.35953985e-02,  -1.39594313e-01,
         -1.60587768e-02,   7.50432777e-02],
       [  1.80390594e-01,   1.33449814e-01,  -1.45953004e-01,
         -5.88862422e-02,  -3.21365790e-02],
       [ -1.93729120e-01,  -1.12561580e-01,  -8.90046489e+00,
         -6.15110785e+01,  -5.70120573e+01],
       [ -7.67306190e-02,  -1.77391714e-01,  -5.66014440e+00,
         -3.91509881e+01,  -3.65473973e+01]]), array([

In [11]:
#training data for "access" 
train_data_size = 50
train_inputs_access = []
train_outputs_access = []

input = []
output = []
for i in range(train_data_size):
    #generated a random array
    input = np.random.randint(1,15,size=(M))
    input_t = stack([get_const(i) for i in input], axis=1)
    #print("input array", input_t.eval().argmax(axis=2))
    train_inputs_access.append(input_t)
    first_elem = input[0]
    output = np.array([[input[first_elem]]])
    output_t = stack([get_const(i) for i in output], axis=1)
    #print(output_t.eval().argmax(axis=2))
    train_outputs_access.append(output_t)
print(train_inputs_access)    
print(train_outputs_access)    


[Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0]
[Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0, Join.0]


In [12]:
def clamp(n, minn, maxn):
    for i, item in enumerate(n):
        n[i] = (map(lambda x: max(min(maxn, x), minn), item))
    return n    
    
def get_l2_norm(w):
    x=0
    for i, item in enumerate(w):
        x += np.linalg.norm(item)
    return x    

def add_noise(gradients, mean, std_dev):
    result = map(lambda x: x + np.random.normal(mean,std_dev,x.shape), gradients)
    return result

#This code is borrowed from http://andrew.gibiansky.com/ based on ADAM optimization technique proposed in the paper
def adam_optimize(params, train, registers, train_inputs, train_outputs, output_len,
                  alpha=0.001, b1=0.9, b2=0.999,
                  epsilon=1e-8, batch_size=1):
    """Implementation of Adam optimization method, with hyperparameters
    taken as recommended by the original publication."""
    # Initialize first and second moment estimates to zero.
    # This causes some bias, which is addressed later.
    moment1 =  [0 for _ in params]
    moment2 = [0 for _ in params]
    
    timestep = 0  # Current optimization step
    batch = 0     # Where does this batch start
    
    converged = False
    gradients = []
    
    while not converged:
        timestep += 1
        
        inputs  = train_inputs[batch:batch+batch_size][0]
        outputs = train_outputs[batch:batch+batch_size][0] 
        
        result = train(registers, inputs.eval(), outputs.eval())
        
        cost = result[0]
        gradients = result[1:]
        
        gradients=add_noise(gradients, 0, 1/(1 + timestep)**0.55)
        
        # Advance to next batch.
        batch = (batch + batch_size) % len(train_inputs)

        # Compute first and second moment estimates.
        # These are decaying moving averages; first moment
        # uses the gradient, second uses squared gradient.
        moment1  = [b1 * m + (1 - b1) * gradient
                    for (m, gradient)
                    in zip(moment1, gradients)]
        moment2 = [b2 * v + (1 - b2) * gradient ** 2
                   for (v, gradient)
                   in zip(moment2, gradients)]
        
        # Correct for initialization bias and compute new values.
        correction1 = 1. / (1 - b1 ** timestep)
        correction2 = 1. / (1 - b2 ** timestep)
        corrected1 = [correction1 * m for m in moment1]
        corrected2 = [correction2 * v for v in moment2]
        
        # Compute new parameter values.
        params_new = [p.get_value() - alpha * m1 / (np.sqrt(m2) + epsilon)
                      for (p, m1, m2) in zip(params, corrected1, corrected2)]

        # Check for convergence by looking at magnitude of delta.
        delta = [abs(p.get_value() - p_new)
                 for (p, p_new) in zip(params, params_new)]
        converged = all((d < 0.5 * alpha).all() for d in delta)        
        
        # Update parameters to new values.
        for p, p_new in zip(params, params_new):
            p_new = clamp(p_new, -1, 1)
            p.set_value(p_new.astype('float32'))
            
        # Provide some output for tracking during runtime.
        if timestep % 100 == 1 or converged:
            print("Cost (t = %4d): \t%.2f" % (timestep - 1, cost))
            print("l2 norm of gradients: ", get_l2_norm(gradients))
            print("l2 norm of p_new: ", get_l2_norm(p_new))

In [14]:
#def adam_optimize(params, train, train_inputs, mem, train_outputs, output_len,
#                  alpha=0.001, b1=0.9, b2=0.999,
#                  epsilon=1e-8, batch_size=1):
    
result = adam_optimize(w, train, registers.eval(), train_inputs_access, train_outputs_access, 1)

Cost (t =    0): 	55.94
('l2 norm of gradients: ', 285.793455006854)
('l2 norm of p_new: ', 4.5805877894559988)
Cost (t =  100): 	29.18
('l2 norm of gradients: ', 125.10614280165575)
('l2 norm of p_new: ', 4.5671700921398637)
Cost (t =  200): 	20.28
('l2 norm of gradients: ', 76.34185983896505)
('l2 norm of p_new: ', 4.4340524510580224)
Cost (t =  300): 	15.42
('l2 norm of gradients: ', 51.627368073352429)
('l2 norm of p_new: ', 4.2914139190237979)
Cost (t =  400): 	12.16
('l2 norm of gradients: ', 38.317028317104501)
('l2 norm of p_new: ', 4.1539377285174481)
Cost (t =  500): 	9.73
('l2 norm of gradients: ', 29.509717728378149)
('l2 norm of p_new: ', 4.0244898837390375)
Cost (t =  600): 	7.83
('l2 norm of gradients: ', 24.121714860937079)
('l2 norm of p_new: ', 3.901720487157943)
Cost (t =  700): 	6.42
('l2 norm of gradients: ', 19.41178266754622)
('l2 norm of p_new: ', 3.7875567193865112)
Cost (t =  800): 	5.42
('l2 norm of gradients: ', 15.962194223920459)
('l2 norm of p_new: ', 3.6

In [15]:
for W in w:
    print(W.eval())

[[ -1.04333892e-01   3.22977230e-02  -2.22566426e-02  -4.08585789e-03
    8.15865934e-01]
 [ -5.50128892e-02   1.04259066e-01  -7.73710608e-02  -2.27401387e-02
    6.19065940e-01]
 [  4.00793999e-02   3.23709875e-01   1.91525947e-02  -6.68770808e-04
    1.00000000e+00]]
[[-0.12018285 -0.05922966 -0.08206513 -0.04878473 -0.17521566]
 [-0.05836811 -0.00440458 -0.39032587 -0.19385818  0.28980574]
 [-0.03296703 -0.03237649 -0.10168082 -0.00597899  0.02717541]
 [ 0.18444966  0.11025048 -0.11753494 -0.02556762 -0.01055628]
 [-0.24266942 -0.06037302  1.          0.20148782  1.        ]
 [-0.02814189 -0.17331459  1.          1.          0.74679756]]
[[  2.00794544e-02  -8.49843249e-02]
 [ -2.28182785e-03   3.34775250e-04]
 [  1.73881888e-01  -2.85365909e-01]
 [  1.91591322e-01  -3.72342616e-02]
 [  3.63736421e-01  -2.29456991e-01]
 [  1.99303031e-01  -4.99068610e-02]]
[[ 0.06535435 -0.0390671   0.02776974]
 [ 0.08767241 -0.03603599 -0.0467042 ]
 [-0.00980904  0.12480929  0.1582879 ]
 [-0.11518

In [26]:
#Access Task
input = [ 7,  1,  12,  4,  7,  12,  1,  13,  8,  2, 1, 3, 11, 11, 12, 0]
output = [ 13 ]
registers = get_registers(0)
memory_tape = stack([get_const(i) for i in input], axis=1)
desired_out = stack([get_const(i) for i in output], axis=1)

In [27]:
v0 = as_tensor(0)
v1 = as_tensor(1)
output = [registers, memory_tape, v0, v0, v1]
new_registers = []
print("registers = ", registers.eval().argmax(axis=2))
print("memory tape:  ", memory_tape.eval().argmax(axis=2))
print("desired tape: ", desired_out.eval().argmax(axis=2))
for timestep in range(MAX_TIMESTEP):
    output = machine_compute_step_t(False, R, layers, w, gates, timestep+1, desired_out, 1, *(output))
    registers, memory_tape, cost_t, cum_prob_t, prob_incomplete = output    
    print("registers = ", registers.eval().argmax(axis=2))
    print("memory tape:  ", memory_tape.eval().argmax(axis=2))
    print("desired tape: ", desired_out.eval().argmax(axis=2))
    print("cost = ", output[2].eval())
    print("prob_incomplete = ", prob_incomplete.eval())

('registers = ', array([[0, 0]]))
('memory tape:  ', array([[ 7,  1, 12,  4,  7, 12,  1, 13,  8,  2,  1,  3, 11, 11, 12,  0]]))
('desired tape: ', array([[13]]))
('registers = ', array([[0, 0]]))
('memory tape:  ', array([[ 7,  1, 12,  4,  7, 12,  1, 13,  8,  2,  1,  3, 11, 11, 12,  0]]))
('desired tape: ', array([[13]]))
('cost = ', array([[[ 0.50540911]]]))
('prob_incomplete = ', array([[[ 0.99784644]]]))
('registers = ', array([[0, 7]]))
('memory tape:  ', array([[ 7,  1, 12,  4,  7, 12,  1, 13,  8,  2,  1,  3, 11, 11, 12,  0]]))
('desired tape: ', array([[13]]))
('cost = ', array([[[ 0.52816157]]]))
('prob_incomplete = ', array([[[ 0.99458004]]]))
('registers = ', array([[7, 7]]))
('memory tape:  ', array([[ 7,  1, 12,  4,  7, 12,  1, 13,  8,  2,  1,  3, 11, 11, 12,  0]]))
('desired tape: ', array([[13]]))
('cost = ', array([[[ 0.5424753]]]))
('prob_incomplete = ', array([[[ 0.98814758]]]))
('registers = ', array([[7, 7]]))
('memory tape:  ', array([[13,  1, 12,  4,  7, 12,  1, 13,

KeyboardInterrupt: 

In [105]:














v0 = as_tensor(0)
v1 = as_tensor(1)
output = [registers, memory_tape, v0, v0, v1]
new_registers = []
print("registers = ", registers.eval().argmax(axis=2))
print("memory tape:  ", memory_tape.eval().argmax(axis=2))
print("desired tape: ", desired_out.eval().argmax(axis=2))
for timestep in range(MAX_TIMESTEP):
    output = machine_compute_step_t(True, R, layers, w, gates, timestep+1, desired_out, 1, *(output))
    registers, memory_tape, cost_t, cum_prob_t, prob_incomplete = output    
    print("registers = ", registers.eval().argmax(axis=2))
    print("memory tape:  ", memory_tape.eval().argmax(axis=2))
    print("desired tape: ", desired_out.eval().argmax(axis=2))
    print("cost = ", output[2].eval())
    print("prob_incomplete = ", prob_incomplete.eval())
    

('registers = ', array([[0, 0]]))
('memory tape:  ', array([[ 7,  1, 12,  4,  7, 12,  1, 13,  8,  2,  1,  3, 11, 11, 12,  0]]))
('desired tape: ', array([[13]]))
('registers: ', array([[[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.]]]))
('registers[:,:,0]: ', array([[ 1.,  1.]]))
('inputs: ', array([[[ 1.,  1.,  1.]]]))
('compute layers inputs: ', array([[[ 1.98015717,  0.        ,  0.        ,  0.        ,  1.63459651,
          1.        ]]]))
('compute layers inputs: ', array([[[ 3.84822199,  0.21068969,  0.        ,  3.94564159,  0.        ,
          1.        ]]]))
('inputs.dot(W)', array([[[ 4.11058133,  4.00697741, -1.31580737, -2.09189066, -0.43671963,
         -1.6898004 , -0.9347702 , -1.40714312]]]))
('inputs.dot(W)[0]', array([[ 4.11058133,  4.00697741, -1.31580737, -2.09189066, -0.43671963,
        -1.6898004 , -0.9347702 , -1.40714